### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by willbarkoff** [CoursesPlus/CoursesPlusInstaller#3]
I can make the logo, but I am not good with java so I cannot implement it.

**Comment by thatoddmailbox** [comment]
Would the logo just say "CoursesPlus Installer"? because if it is, then you can just draw it as text, which would be easier.

**Comment by willbarkoff** [comment]
I was saying for the dock.

**Comment by willbarkoff** [comment]
Here is the type of logo I was thinking of:
[coursesplus installer logo](https://cloud.githubusercontent.com/assets/10969136/9716766/fe268d68-553a-11e5-8a8c-eebf98232e9c.png)
Some things to think about:
- Moving "CoursesPlus Installer" text
- Changing box color

**Comment by thatoddmailbox** [comment]
@nywillb You'd probably want to antialias the curves (see the jagged edges on the C?)

Also, I found [a StackOverflow post](http://stackoverflow.com/questions/6006173/how-do-you-change-the-dock-icon-of-a-java-program) with information on setting the dock icon.

**Comment by willbarkoff** [comment]
Is this good?
![coursesplus installer logo](https://cloud.githubusercontent.com/assets/10969136/9722246/84de8e46-5577-11e5-9fbe-d1f5a027591e.png)

**Comment by thatoddmailbox** [comment]
@nywillb That's nice.

**Comment by willbarkoff** [comment]
@thatoddmailbox Thanks. I am about to commit, can you make it into a jar for me so I can test?

**Comment by thatoddmailbox** [comment]
@nywillb Let me get my student laptop first. I have to figure out how to pack images in to a jar first though.

**Comment by willbarkoff** [comment]
@thatoddmailbox Okay, thanks

**Comment by thatoddmailbox** [comment]
@nywillb It doesn't seem like the Application.getApplication() method works anymore - I'm getting an access restriction error when I try to compile...

**Comment by willbarkoff** [comment]
@thatoddmailbox Which method do you think I should use. [Here](http://stackoverflow.com/questions/6006173/how-do-you-change-the-dock-icon-of-a-java-program) is the post you sent me.

**Comment by thatoddmailbox** [comment]
@nywillb 
I think we have to have the jar relaunch itself with the -Xdock:image parameter..
Can you get on the Pitch presentation or some other Google doc? GitHub Issues doesn't work well for real-time chatting...

**Comment by willbarkoff** [comment]
@thatoddmailbox Sure, I will go on the presentation now.

**Comment by medensqui** [comment]
Am I a part of this Prez?

**Comment by thatoddmailbox** [comment]
@medensqui DON'T REOPEN THIS ISSUE WE DID IT ALREADY

Also, @nywillb moved it to a Keynote presentation and I was just using it as a document to chat on.

But I shared it with you now.
